version: "3.9"

services:
  gateway:
    container_name: varlor-gateway
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - varlor-net

networks:
  varlor-net:
    driver: bridge