apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: product-api-hpa
  namespace: default
  labels:
    app: product-api
    component: backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-api
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
# PodDisruptionBudget pour la haute disponibilité
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: product-api-pdb
  namespace: default
  labels:
    app: product-api
    component: backend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: product-api