apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-client-hpa
  namespace: default
  labels:
    app: web-client
    component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-client
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80

---
# PodDisruptionBudget pour la haute disponibilité
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: web-client-pdb
  namespace: default
  labels:
    app: web-client
    component: frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: web-client

---
# NetworkPolicy pour sécuriser l'accès réseau
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: web-client-network-policy
  namespace: default
  labels:
    app: web-client
    component: frontend
spec:
  podSelector:
    matchLabels:
      app: web-client
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      # Autoriser l'ingress controller
      - namespaceSelector:
          matchLabels:
            name: ingress-nginx
      # Autoriser les autres services backend
      - podSelector:
          matchLabels:
            component: backend
    ports:
      - protocol: TCP
        port: 80
  egress:
    # Autoriser les connexions sortantes nécessaires
    - to: []
      ports:
        - protocol: TCP
          port: 443  # HTTPS pour les ressources externes
        - protocol: TCP
          port: 53   # DNS
        - protocol: UDP
          port: 53   # DNS
    # Autoriser la communication avec les APIs backend
    - to:
      - podSelector:
          matchLabels:
            app: gateway
      ports:
        - protocol: TCP
          port: 8080
    - to:
      - podSelector:
          matchLabels:
            app: ai-api
      ports:
        - protocol: TCP
          port: 3000
    - to:
      - podSelector:
          matchLabels:
            app: product-api
      ports:
        - protocol: TCP
          port: 80
    - to:
      - podSelector:
          matchLabels:
            app: calculations-api
      ports:
        - protocol: TCP
          port: 8000